

GET http://localhost:8000/api/ok/

###

GET http://localhost:8000/api/bookings/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtdWt3YW5hQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzIxNjg2MjE5fQ.kWhKTuOaIDqS441O0ponfUICLjlDCLFgTaonuzYt-SI
Content-Type: application/json

{
 "vehicleSpecId": 2,
  "vehicleId": 1,
  "rentalRate": "56",
  "availability": "availabl",
  "createdAt": "2024-07-06T08:31:19.894Z",
  "updatedAt": "2024-07-06T08:31:19.894Z",
  "vehicleImage": null,
}
###update
PUT http://localhost:8000/api/vehicles/1
Content-Type: application/json

{
  "vehicleSpecId": 2,
  "vehicleId": 1,
  "rentalRate": "56",
  "availability": "availabl",
  "createdAt": "2024-07-06T08:31:19.894Z",
  "updatedAt": "2024-07-06T08:31:19.894Z",
  "vehicleImage": null
}

###User Registration
POST http://localhost:8000/api/auth/register
Content-Type: application/json

{   "userId":14,
    "fullName":"Jo Bradley",
    "email":"no@gmail.com",
    "password":"1234"
}
###
POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
   "email":"jo@gmail.com",
    "password":"1234"

}
###
DELETE http://localhost:8000/api/users/90
