

GET http://localhost:8000/api/ok/

###

GET http://localhost:8000/api/users/1
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtd2FuZ2lAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzIwNzk3NTI5fQ.fsooeYl2tbk5uBiTZspUbYmcpPO5a8sX17_p1byfSno

###
POST http://localhost:8000/api/vehicleSpecifications
Content-Type: application/json

{
    "vehicleId": 4,
    "manufacturer": "Audi",
    "model": "A8",
    "year": 2021,
    "fuelType": "petrol",
    "engineCapacity": "3.0L",
    "transmission": "automatic",
    "seatingCapacity": 5,
    "color": "black",
    "features": [
        "Leather seats",
        "sunroof",
        "navigation system",
        "parking sensors",
        "rear camera",
        "heated seats",
        "heated steering wheel",
        "adaptive cruise control",
        "lane departure warning",
        "blind spot monitoring",
        "automatic emergency braking",
        "forward collision warning",
        "automatic high-beam headlights",
        "rain-sensing wipers",
        "dual-zone automatic climate control",
        "power-adjustable front seats",
        "memory driver's seat",
        "power-adjustable steering wheel",
        "power-folding rear seats",
        "power liftgate",
        "keyless entry",
        "push-button start",
        "remote start"
        ]
}

###
POST http://localhost:8000/api/auth/register
Content-Type: application/json

{  
    
    "userId":2 ,
    "fullName":"john mwangi",
    "email":"mwangi@gmail.com",
    "password":"1234",
     "role":"admin"
}
###
POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
   "email":"mwangi@gmail.com",
    "password":"1234"

}
###
DELETE http://localhost:8000/api/bookings/5
